"""
String constants used throughout the message processing pipeline module.

This module centralizes all string literals to improve maintainability and
prevent typos by using constants instead of string literals.
"""

# Stage Names
STAGE_VALIDATION = "VALIDATION"
STAGE_SESSION_RESOLUTION = "SESSION_RESOLUTION"
STAGE_SUBSCRIBER_RESOLUTION = "SUBSCRIBER_RESOLUTION"
STAGE_SESSION_CREATION = "SESSION_CREATION"
STAGE_SESSION_START = "SESSION_START"
STAGE_SESSION_BINDING = "SESSION_BINDING"
STAGE_SESSION_REFRESH = "SESSION_REFRESH"
STAGE_SESSION_TERMINATE = "SESSION_TERMINATE"
STAGE_SESSION_UPDATE = "SESSION_UPDATE"
STAGE_ERROR_HANDLING = "ERROR_HANDLING"
STAGE_MESSAGE_STORAGE = "MESSAGE_STORAGE"
STAGE_CLEANUP = "CLEANUP"

# Message Flow Types
FLOW_START = "START"
FLOW_UPDATE = "UPDATE"
FLOW_REFRESH = "REFRESH"
FLOW_TERMINATE = "TERMINATE"
FLOW_UNKNOWN = "UNKNOWN"

# Session Binding Methods
BINDING_DISABLED = "DISABLED"
BINDING_NONE = "NONE"
BINDING_ALREADY_BOUND = "ALREADY_BOUND"
BINDING_FRAMED_IP = "FRAMED_IP"
BINDING_SUBSCRIBER_SESSION_ID = "SUBSCRIBER_SESSION_ID"
BINDING_MSISDN = "MSISDN"
BINDING_IMSI = "IMSI"
BINDING_FAILED = "FAILED"

# Subscriber Resolution Methods
RESOLUTION_EXISTING_SESSION = "EXISTING_SESSION"
RESOLUTION_SESSION = "SESSION"
RESOLUTION_MSISDN = "MSISDN"
RESOLUTION_IMSI = "IMSI"
RESOLUTION_FRAMED_IP = "FRAMED_IP"
RESOLUTION_CREATED = "CREATED"

# Diameter Message Names
MSG_RAR = "RAR"  # Re-Auth-Request
MSG_ASR = "ASR"  # Abort-Session-Request
MSG_CCR_T = "CCR-T"  # Credit-Control-Request-Terminate
MSG_STR = "STR"  # Session-Termination-Request

# Application Names (for logging)
APP_NAME_RX = "Rx"
APP_NAME_SY = "Sy"
APP_NAME_GY = "Gy"
