from diameter.message.constants import *

CCR_I = "CCR-I"
CCA_I = "CCA-I"
CCR_U = "CCR-U"
CCA_U = "CCA-U"
CCR_T = "CCR-T"
CCA_T = "CCA-T"
RAR = "RAR"
RAA = "RAA"
AAR = "AAR"
AAA = "AAA"
STR = "STR"
STA = "STA"
ASR = "ASR"
ASA = "ASA"
SLR = "SLR"
SLA = "SLA"
SSNR = "SSNR"
SSNA = "SSNA"
DWR = "DWR"
DWA = "DWA"
CER = "CER"
CEA = "CEA"
